### ISSUE TITLE
TestImage errors out in IJulia

### ISSUE THREAD

**Issue by tlnagy** [timholy/TestImages.jl#11]
When using TestImage as follows with Julia v0.4.1,

```{.julia}
using TestImages
im = TestImages("mandrill")
```
I get the following error:

```{.julia}
LoadError: MethodError: `call` has no method matching call(::Module, ::ASCIIString)
Closest candidates are:
  BoundsError()
  BoundsError(!Matched::Any...)
  DivideError()
  ...
while loading In[1], in expression starting on line 2
```

Here's my Pkg status output:
```
julia> Pkg.status()
8 required packages:
 - Color                         0.2.11
 - Gadfly                        0.4.0
 - IJulia                        1.1.8
 - ImageMagick                   0.1.1              master
 - Images                        0.5.0+             master
 - QuartzImageIO                 0.1.0
 - RDatasets                     0.1.2
 - TestImages                    0.1.0
49 additional packages:
 - ArrayViews                    0.6.4
 - BinDeps                       0.3.19
 - Calculus                      0.1.14
 - Codecs                        0.1.5
 - ColorTypes                    0.2.0
 - ColorVectorSpace              0.1.0
 - Colors                        0.6.0
 - Compat                        0.7.8
 - Compose                       0.4.0
 - Conda                         0.1.8
 - Contour                       0.0.8
 - DataArrays                    0.2.20
 - DataFrames                    0.6.10
 - DataStructures                0.3.13
 - Dates                         0.4.4
 - Distances                     0.2.1
 - Distributions                 0.8.7
 - Docile                        0.5.19
 - DualNumbers                   0.1.5
 - FileIO                        0.0.3
 - FixedPointNumbers             0.1.1
 - GZip                          0.2.18
 - Graphics                      0.1.3
 - Grid                          0.4.0
 - Hexagons                      0.0.4
 - Homebrew                      0.2.0
 - ImmutableArrays               0.0.11
 - Iterators                     0.1.9
 - JSON                          0.5.0
 - KernelDensity                 0.1.2
 - Loess                         0.0.6
 - Measures                      0.0.1
 - NaNMath                       0.1.1
 - Nettle                        0.2.0
 - Optim                         0.4.4
 - PDMats                        0.3.6
 - Reexport                      0.0.3
 - SHA                           0.1.2
 - SIUnits                       0.0.6
 - Showoff                       0.0.6
 - SortingAlgorithms             0.0.6
 - StatsBase                     0.7.4
 - StatsFuns                     0.2.0
 - TexExtensions                 0.0.3
 - URIParser                     0.1.1
 - WoodburyMatrices              0.1.2
 - ZMQ                           0.3.1
 - ZipFile                       0.2.5
 - Zlib                          0.1.12
```

**Comment by timholy** [comment]
Try `img = testimage("mandrill")`. Note the lack of capitalization and the lack of an `s` at the end.

It's also worth pointing out that in julia, `im` is the imaginary-number constant. It's fine to reassign it as you've done above, but just so you know (in case you want to use it for something in the same session).

**Comment by tlnagy** [comment]
Thanks for the pointers. I restarted the kernel and tried the following:

```{.julia}
using Images
using TestImages
using ImageMagick
img = testimage("autumn_leaves")
```
and I got:

```
 in error at /usr/local/Cellar/julia/0.4.1/lib/julia/sys.dylib
 in error at /Users/tamasnagy/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in setimageformat at /Users/tamasnagy/.julia/v0.4/ImageMagick/src/libmagickwand.jl:346
 in getblob at /Users/tamasnagy/.julia/v0.4/ImageMagick/src/libmagickwand.jl:212
 in writemime_ at /Users/tamasnagy/.julia/v0.4/ImageMagick/src/ImageMagick.jl:250
 in writemime at /Users/tamasnagy/.julia/v0.4/Images/src/writemime.jl:28
 in base64encode at base64.jl:160
 in display_dict at /Users/tamasnagy/.julia/v0.4/IJulia/src/execute_request.jl:32



 in error at /usr/local/Cellar/julia/0.4.1/lib/julia/sys.dylib
 in error at /Users/tamasnagy/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in setimageformat at /Users/tamasnagy/.julia/v0.4/ImageMagick/src/libmagickwand.jl:346
 in getblob at /Users/tamasnagy/.julia/v0.4/ImageMagick/src/libmagickwand.jl:212
 in writemime_ at /Users/tamasnagy/.julia/v0.4/ImageMagick/src/ImageMagick.jl:250
 in writemime at /Users/tamasnagy/.julia/v0.4/Images/src/writemime.jl:28
 in base64encode at base64.jl:160
 in display_dict at /Users/tamasnagy/.julia/v0.4/IJulia/src/execute_request.jl:32
```

**Comment by timholy** [comment]
You may want to try these:
https://github.com/timholy/Images.jl/blob/master/doc/install.md#fixing-broken-installations-on-macs
https://github.com/JuliaLang/Homebrew.jl/wiki/Debugging-Homebrew.jl

Also, try `Pkg.rm("ImageMagick"); Pkg.add("QuartzImageIO")`. That may be good enough to support reading.

**Comment by tlnagy** [comment]
I forgot about this issue, but ran into a problem with this again. Your first link is broken?

**Comment by Evizero** [comment]
I am having the same problem in the jupyter notebook on OS X. `QuartzImageIO` does nothing, or at least trying to display the image results in a suggestion to use `ImageMagick`. I got it to run without an error by checking out the latest master for `ImageView` and `ImageMagic` and calling the following code. However, nothing is displayed.

```julia
using TestImages
using ImageMagick
using ImageView
img = testimage("mandrill")
```

not sure where to go from here. any pointers?

**Comment by Evizero** [comment]
Ok I fixed it. it was quite involved. The issue is I had image magick already installed with my global homebrew installation and that messed everything up. It seems Homebrew.jl tried to use this global installation but failed to do so. The "debugging homebrew" tip didn't work after this point, because imagemagick was to interweaved it seems. I had to completely delete the folders for Homebrew.jl, and ImageMagick.jl (I also did that for Images.jl and ImageView.jl to be safe), and then deinstall imagemagick from the global homebrew, before running Julia. naturally messing with the Homebrew.jl folder means I had to build a couple of packages before they were usable again (like IJulia). All in all this was quite messy.

Pro tip: do not by the love of god install imagemagick using the global homebrew installation

**Comment by tlnagy** [comment]
Is there anyway to do this without breaking the global install of imagemagick? I need it for other things.

**Comment by Evizero** [comment]
Sorry, but I don't know. I took the path of least resistance. I am not even 100% certain I identified down the true cause. All I know is it works now. 

One might get away with installing imagemagick using homebrew after the Julia one is set up properly, but I didn't try (yet).

**Comment by timholy** [comment]
Regarding QuartzImageIO, you might need to be on master (`Pkg.checkout("QuartzImageIO")`). It hasn't been tagged in a while (CC @rsrock).

**Comment by tlnagy** [comment]
Running `Pkg.checkout("QuartzImageIO"); Pkg.build("QuartzImageIO")` did the trick. I'm now getting images displayed properly in IJulia after running `using QuartzImageIO`. 

The QuartzImageIO README suggests that I shouldn't do this though? 

> QuartzImageIO will be used as needed if you've said

> `using FileIO`

> in your session or module. You should not generally say `using QuartzImageIO`. See FileIO for further details.

However, `using FileIO` followed by `img = load("test.png")` still gives me the following error:

```{.julia}
No IO library loaded for writemime image/png with Images.Image{ColorTypes.RGB4{FixedPointNumbers.UFixed{UInt8,8}},2,Array{ColorTypes.RGB4{FixedPointNumbers.UFixed{UInt8,8}},2}}.
            Please consider putting "using ImageMagick" in your script

 in error at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in writemime at /Users/tamasnagy/.julia/v0.4/Images/src/writemime.jl:30
 in base64encode at base64.jl:160
 in display_dict at /Users/tamasnagy/.julia/v0.4/IJulia/src/execute_request.jl:32
```
which points me to ImageMagick, which has other problems. I feel like this is really confusing for new users.

**Comment by timholy** [comment]
>  I feel like this is really confusing for new users.

It certainly is. It's even confusing to the developers :smile:, trying to support the idiosyncrasies of multiple platforms that some of us don't even have access to.

To clarify what's happening, I bet you're using IJulia, and that if you put a semicolon after your `load` command you will avoid that error. If my guess is correct, it means that the error is being triggered by the attempt to display the image, but that the loading worked just fine.

It seems that QuartzImageIO probably needs the analog of [this function](https://github.com/JuliaIO/ImageMagick.jl/blob/70ce54334109044636417f3ce66b5ac27afad448/src/ImageMagick.jl#L255-L259). Care to give it a try? (Lacking a mac, I can't test this myself.)

**Comment by Evizero** [comment]
> To clarify what's happening, I bet you're using IJulia, and that if you put a semicolon after your load command you will avoid that error. If my guess is correct, it means that the error is being triggered by the attempt to display the image, but that the loading worked just fine.

I can answer this with a yes

> It seems that QuartzImageIO probably needs the analog of this function. Care to give it a try?

I may take a shot at this as I currently have to work with Images a lot and just recently bought myself a macbook for travel and presentations (i.e. I'm looking for excuses to use it :) ). It may take a few days/weeks though.

**Comment by tlnagy** [comment]
> To clarify what's happening, I bet you're using IJulia, and that if you put a semicolon after your load command you will avoid that error. 

Can confirm

> It seems that QuartzImageIO probably needs the analog of this function. Care to give it a try? (Lacking a mac, I can't test this myself.)

@timholy Doesn't QuartzImageIO already have this function? https://github.com/JuliaIO/QuartzImageIO.jl/blob/master/src/QuartzImageIO.jl#L270-L273

**Comment by timholy** [comment]
@tlnagy, good point!

OK, this _may_ be a case where you _should_ say `using QuartzImageIO` before use. If that fixes your problem, we should change the README and also modify the error message in Images.

[This code](https://github.com/timholy/Images.jl/blob/824a8ea26e1103feb43ea9ce0f6c7bbff901bc85/src/writemime.jl#L26-L33) seems like it's not working ideally. @SimonDanisch, I think that's your work from https://github.com/timholy/Images.jl/pull/380. Care to chime in? I'm not sure what the `CurrentModule` stuff is supposed to achieve. (It also looks like there might be a bug, in that the `isdefined` call was perhaps intended to be `isdefined(CurrentModule, :writemime_)`. Or perhaps we should get rid of the `CurrentModule` stuff altogether?)

**Comment by SimonDanisch** [comment]
Huh...yeah there was some problem because `FileIO` only imports the IO libraries.
I would think, `defined(CurrentModule, :writemime_)` could solve it?

>Pro tip: do not by the love of god install imagemagick using the global homebrew installation

It should work in theory, though! Maybe someone needs to do the same thing I did in https://github.com/JuliaIO/ImageMagick.jl/pull/28 for `OSX`...

**Comment by timholy** [comment]
I put in a `@show CurrentModule`. When I try IJulia, for me `CurrentModule` is `Main`. That won't help if the user hadn't already say `using ImageMagick` or `using QuartzImageIO`.

In other words, this isn't an OSX-only problem; I doubt it's doing anything useful on Linux, either, and presumably Windows is the same.

**Comment by SimonDanisch** [comment]
Okay... So I guess it wasn't a very good fix for whatever problem I had...
So this means FileIO needs to export `writemime_` and every loaded IO module needs to overload it for it's own type? That'd mean IO libraries can overwrite it, but I guess that should be okay, as long as the IO library does the job!

**Comment by timholy** [comment]
I haven't thought it through carefully. Maybe `FileIO` could do internal module-wise dispatch on `writemime_`, similarly to how `load` and `save` are handled?

**Comment by SimonDanisch** [comment]
That was our initial idea, wasn't it? But maybe we got only stuck because of a lack of creativity ;)

**Comment by tlnagy** [comment]
Thanks to @timholy and @Evizero's hard work the following works in IJulia using the latest masters of FileIO, QuartzImageIO, and Image:

```{.julia}
using FileIO, Image, TestImage,
img = testimage("mandrill")
```

🎉

**Comment by Evizero** [comment]
> using the latest masters

I don't think you have to be on master for this, since those changes are already tagged

**Comment by timholy** [comment]
Thanks, I meant to ask whether this worked with all the tagged versions. I take that as a yes.

**Comment by tlnagy** [comment]
I think it might have been due to me having local changes on `QuartzImageIO`. I ran `Pkg.free([Images, FileIO, QuartzImageIO])` and `Pkg.update()`

Now my versions are:
```
 - FileIO                        0.0.4
 - Images                        0.4.50
 - QuartzImageIO                 0.0.2
```
and it works in IJulia.

**Comment by timholy** [comment]
Great, thanks for checking.
